var pk_items = [["大师球", "Master Ball"], 
["高级球", "Ultra Ball"], 
["超级球", "Great Ball"], 
["精灵球", "Poké Ball"], 
["狩猎球", "Safari Ball"], 
["捕网球", "Net Ball"], 
["潜水球", "Dive Ball"], 
["巢穴球", "Nest Ball"], 
["重复球", "Repeat Ball"], 
["计时球", "Timer Ball"], 
["豪华球", "Luxury Ball"], 
["纪念球", "Premier Ball"], 
["黑暗球", "Dusk Ball"], 
["治愈球", "Heal Ball"], 
["先机球", "Quick Ball"], 
["贵重球", "Cherish Ball"], 
["伤药", "Potion"], 
["解毒药", "Antidote"], 
["灼伤药", "Burn Heal"], 
["解冻药", "Ice Heal"], 
["解眠药", "Awakening"], 
["解麻药", "Paralyze Heal"], 
["全复药", "Full Restore"], 
["全满药", "Max Potion"], 
["厉害伤药", "Hyper Potion"], 
["好伤药", "Super Potion"], 
["万灵药", "Full Heal"], 
["活力碎片", "Revive"], 
["活力块", "Max Revive"], 
["美味之水", "Fresh Water"], 
["劲爽汽水", "Soda Pop"], 
["果汁牛奶", "Lemonade"], 
["哞哞鲜奶", "Moomoo Milk"], 
["元气粉", "Energy Powder"], 
["元气根", "Energy Root"], 
["万能粉", "Heal Powder"], 
["复活草", "Revival Herb"], 
["ＰＰ单项小补剂", "Ether"], 
["ＰＰ单项全补剂", "Max Ether"], 
["ＰＰ多项小补剂", "Elixir"], 
["ＰＰ多项全补剂", "Max Elixir"], 
["ＨＰ增强剂", "HP Up"], 
["攻击增强剂", "Protein"], 
["防御增强剂", "Iron"], 
["速度增强剂", "Carbos"], 
["特攻增强剂", "Calcium"], 
["神奇糖果", "Rare Candy"], 
["ＰＰ提升剂", "PP Up"], 
["特防增强剂", "Zinc"], 
["ＰＰ极限提升剂", "PP Max"], 
["能力防守", "Guard Spec."], 
["要害攻击", "Dire Hit"], 
["力量强化", "X Attack"], 
["防御强化", "X Defense"], 
["速度强化", "X Speed"], 
["命中强化", "X Accuracy"], 
["特攻强化", "X Sp. Atk"], 
["特防强化", "X Sp. Def"], 
["皮皮玩偶", "Poké Doll"], 
["日之石", "Sun Stone"], 
["月之石", "Moon Stone"], 
["火之石", "Fire Stone"], 
["雷之石", "Thunder Stone"], 
["水之石", "Water Stone"], 
["叶之石", "Leaf Stone"], 
["小蘑菇", "Tiny Mushroom"], 
["大蘑菇", "Big Mushroom"], 
["珍珠", "Pearl"], 
["大珍珠", "Big Pearl"], 
["星星沙子", "Stardust"], 
["星星碎片", "Star Piece"], 
["金珠", "Nugget"], 
["甜甜蜜", "Honey"], 
["贵重骨头", "Rare Bone"], 
["光之石", "Shiny Stone"], 
["暗之石", "Dusk Stone"], 
["觉醒之石", "Dawn Stone"], 
["浑圆之石", "Oval Stone"], 
["楔石", "Odd Keystone"], 
["白金宝珠", "Griseous Orb"], 
["金刚宝珠", "Adamant Orb"], 
["白玉宝珠", "Lustrous Orb"], 
["樱子果", "Cheri Berry"], 
["零余果", "Chesto Berry"], 
["桃桃果", "Pecha Berry"], 
["莓莓果", "Rawst Berry"], 
["利木果", "Aspear Berry"], 
["苹野果", "Leppa Berry"], 
["橙橙果", "Oran Berry"], 
["柿仔果", "Persim Berry"], 
["木子果", "Lum Berry"], 
["文柚果", "Sitrus Berry"], 
["勿花果", "Figy Berry"], 
["异奇果", "Wiki Berry"], 
["芒芒果", "Mago Berry"], 
["乐芭果", "Aguav Berry"], 
["芭亚果", "Iapapa Berry"], 
["榴石果", "Pomeg Berry"], 
["藻根果", "Kelpsy Berry"], 
["比巴果", "Qualot Berry"], 
["哈密果", "Hondew Berry"], 
["萄葡果", "Grepa Berry"], 
["茄番果", "Tamato Berry"], 
["巧可果", "Occa Berry"], 
["千香果", "Passho Berry"], 
["烛木果", "Wacan Berry"], 
["罗子果", "Rindo Berry"], 
["番荔果", "Yache Berry"], 
["莲蒲果", "Chople Berry"], 
["通通果", "Kebia Berry"], 
["腰木果", "Shuca Berry"], 
["棱瓜果", "Coba Berry"], 
["福禄果", "Payapa Berry"], 
["扁樱果", "Tanga Berry"], 
["草蚕果", "Charti Berry"], 
["佛柑果", "Kasib Berry"], 
["莓榴果", "Haban Berry"], 
["刺耳果", "Colbur Berry"], 
["霹霹果", "Babiri Berry"], 
["灯浆果", "Chilan Berry"], 
["枝荔果", "Liechi Berry"], 
["龙睛果", "Ganlon Berry"], 
["沙鳞果", "Salac Berry"], 
["龙火果", "Petaya Berry"], 
["杏仔果", "Apicot Berry"], 
["兰萨果", "Lansat Berry"], 
["星桃果", "Starf Berry"], 
["谜芝果", "Enigma Berry"], 
["奇秘果", "Micle Berry"], 
["释陀果", "Custap Berry"], 
["嘉珍果", "Jaboca Berry"], 
["雾莲果", "Rowap Berry"], 
["光粉", "Bright Powder"], 
["白色香草", "White Herb"], 
["先制之爪", "Quick Claw"], 
["安抚之铃", "Soothe Bell"], 
["心灵香草", "Mental Herb"], 
["讲究头带", "Choice Band"], 
["王者之证", "King’s Rock"], 
["银粉", "Silver Powder"], 
["护符金币", "Amulet Coin"], 
["洁净之符", "Cleanse Tag"], 
["心之水滴", "Soul Dew"], 
["烟雾球", "Smoke Ball"], 
["不变之石", "Everstone"], 
["气势头带", "Focus Band"], 
["幸运蛋", "Lucky Egg"], 
["焦点镜", "Scope Lens"], 
["金属膜", "Metal Coat"], 
["吃剩的东西", "Leftovers"], 
["龙之鳞片", "Dragon Scale"], 
["电气球", "Light Ball"], 
["柔软沙子", "Soft Sand"], 
["硬石头", "Hard Stone"], 
["奇迹种子", "Miracle Seed"], 
["黑色眼镜", "Black Glasses"], 
["黑带", "Black Belt"], 
["磁铁", "Magnet"], 
["神秘水滴", "Mystic Water"], 
["锐利鸟嘴", "Sharp Beak"], 
["毒针", "Poison Barb"], 
["不融冰", "Never-Melt Ice"], 
["咒术之符", "Spell Tag"], 
["弯曲的汤匙", "Twisted Spoon"], 
["木炭", "Charcoal"], 
["龙之牙", "Dragon Fang"], 
["丝绸围巾", "Silk Scarf"], 
["升级数据", "Upgrade"], 
["贝壳之铃", "Shell Bell"], 
["广角镜", "Wide Lens"], 
["力量头带", "Muscle Band"], 
["博识眼镜", "Wise Glasses"], 
["达人带", "Expert Belt"], 
["光之黏土", "Light Clay"], 
["生命宝珠", "Life Orb"], 
["强力香草", "Power Herb"], 
["剧毒宝珠", "Toxic Orb"], 
["火焰宝珠", "Flame Orb"], 
["气势披带", "Focus Sash"], 
["对焦镜", "Zoom Lens"], 
["节拍器", "Metronome"], 
["黑色铁球", "Iron Ball"], 
["后攻之尾", "Lagging Tail"], 
["红线", "Destiny Knot"], 
["黑色污泥", "Black Sludge"], 
["冰冷岩石", "Icy Rock"], 
["沙沙岩石", "Smooth Rock"], 
["炽热岩石", "Heat Rock"], 
["潮湿岩石", "Damp Rock"], 
["紧缠钩爪", "Grip Claw"], 
["讲究围巾", "Choice Scarf"], 
["附着针", "Sticky Barb"], 
["力量护腕", "Power Bracer"], 
["力量腰带", "Power Belt"], 
["力量镜", "Power Lens"], 
["力量束带", "Power Band"], 
["力量护踝", "Power Anklet"], 
["力量负重", "Power Weight"], 
["美丽空壳", "Shed Shell"], 
["大根茎", "Big Root"], 
["讲究眼镜", "Choice Specs"], 
["火球石板", "Flame Plate"], 
["水滴石板", "Splash Plate"], 
["雷电石板", "Zap Plate"], 
["碧绿石板", "Meadow Plate"], 
["冰柱石板", "Icicle Plate"], 
["拳头石板", "Fist Plate"], 
["剧毒石板", "Toxic Plate"], 
["大地石板", "Earth Plate"], 
["蓝天石板", "Sky Plate"], 
["神奇石板", "Mind Plate"], 
["玉虫石板", "Insect Plate"], 
["岩石石板", "Stone Plate"], 
["妖怪石板", "Spooky Plate"], 
["龙之石板", "Draco Plate"], 
["恶颜石板", "Dread Plate"], 
["钢铁石板", "Iron Plate"], 
["护具", "Protector"], 
["电力增幅器", "Electirizer"], 
["熔岩增幅器", "Magmarizer"], 
["可疑补丁", "Dubious Disc"], 
["灵界之布", "Reaper Cloth"], 
["锐利之爪", "Razor Claw"], 
["锐利之牙", "Razor Fang"], 
["招式学习器０１", "TM01"], 
["招式学习器０２", "TM02"], 
["招式学习器０３", "TM03"], 
["招式学习器０４", "TM04"], 
["招式学习器０５", "TM05"], 
["招式学习器０６", "TM06"], 
["招式学习器０７", "TM07"], 
["招式学习器０８", "TM08"], 
["招式学习器０９", "TM09"], 
["招式学习器１０", "TM10"], 
["招式学习器１１", "TM11"], 
["招式学习器１２", "TM12"], 
["招式学习器１３", "TM13"], 
["招式学习器１４", "TM14"], 
["招式学习器１５", "TM15"], 
["招式学习器１６", "TM16"], 
["招式学习器１７", "TM17"], 
["招式学习器１８", "TM18"], 
["招式学习器１９", "TM19"], 
["招式学习器２０", "TM20"], 
["招式学习器２１", "TM21"], 
["招式学习器２２", "TM22"], 
["招式学习器２３", "TM23"], 
["招式学习器２４", "TM24"], 
["招式学习器２５", "TM25"], 
["招式学习器２６", "TM26"], 
["招式学习器２７", "TM27"], 
["招式学习器２８", "TM28"], 
["招式学习器２９", "TM29"], 
["招式学习器３０", "TM30"], 
["招式学习器３１", "TM31"], 
["招式学习器３２", "TM32"], 
["招式学习器３３", "TM33"], 
["招式学习器３４", "TM34"], 
["招式学习器３５", "TM35"], 
["招式学习器３６", "TM36"], 
["招式学习器３７", "TM37"], 
["招式学习器３８", "TM38"], 
["招式学习器３９", "TM39"], 
["招式学习器４０", "TM40"], 
["招式学习器４１", "TM41"], 
["招式学习器４２", "TM42"], 
["招式学习器４３", "TM43"], 
["招式学习器４４", "TM44"], 
["招式学习器４５", "TM45"], 
["招式学习器４６", "TM46"], 
["招式学习器４７", "TM47"], 
["招式学习器４８", "TM48"], 
["招式学习器４９", "TM49"], 
["招式学习器５０", "TM50"], 
["招式学习器５１", "TM51"], 
["招式学习器５２", "TM52"], 
["招式学习器５３", "TM53"], 
["招式学习器５４", "TM54"], 
["招式学习器５５", "TM55"], 
["招式学习器５６", "TM56"], 
["招式学习器５７", "TM57"], 
["招式学习器５８", "TM58"], 
["招式学习器５９", "TM59"], 
["招式学习器６０", "TM60"], 
["招式学习器６１", "TM61"], 
["招式学习器６２", "TM62"], 
["招式学习器６３", "TM63"], 
["招式学习器６４", "TM64"], 
["招式学习器６５", "TM65"], 
["招式学习器６６", "TM66"], 
["招式学习器６７", "TM67"], 
["招式学习器６８", "TM68"], 
["招式学习器６９", "TM69"], 
["招式学习器７０", "TM70"], 
["招式学习器７１", "TM71"], 
["招式学习器７２", "TM72"], 
["招式学习器７３", "TM73"], 
["招式学习器７４", "TM74"], 
["招式学习器７５", "TM75"], 
["招式学习器７６", "TM76"], 
["招式学习器７７", "TM77"], 
["招式学习器７８", "TM78"], 
["招式学习器７９", "TM79"], 
["招式学习器８０", "TM80"], 
["招式学习器８１", "TM81"], 
["招式学习器８２", "TM82"], 
["招式学习器８３", "TM83"], 
["招式学习器８４", "TM84"], 
["招式学习器８５", "TM85"], 
["招式学习器８６", "TM86"], 
["招式学习器８７", "TM87"], 
["招式学习器８８", "TM88"], 
["招式学习器８９", "TM89"], 
["招式学习器９０", "TM90"], 
["招式学习器９１", "TM91"], 
["招式学习器９２", "TM92"], 
["红球果", "Red Apricorn"], 
["蓝球果", "Blue Apricorn"], 
["黄球果", "Yellow Apricorn"], 
["绿球果", "Green Apricorn"], 
["粉球果", "Pink Apricorn"], 
["白球果", "White Apricorn"], 
["黑球果", "Black Apricorn"], 
["速度球", "Fast Ball"], 
["等级球", "Level Ball"], 
["诱饵球", "Lure Ball"], 
["沉重球", "Heavy Ball"], 
["甜蜜球", "Love Ball"], 
["友友球", "Friend Ball"], 
["月亮球", "Moon Ball"], 
["竞赛球", "Sport Ball"], 
["公园球", "Park Ball"], 
["美丽鳞片", "Prism Scale"], 
["进化奇石", "Eviolite"], 
["轻石", "Float Stone"], 
["凸凸头盔", "Rocky Helmet"], 
["气球", "Air Balloon"], 
["红牌", "Red Card"], 
["标靶", "Ring Target"], 
["紧绑束带", "Binding Band"], 
["球根", "Absorb Bulb"], 
["充电电池", "Cell Battery"], 
["逃脱按键", "Eject Button"], 
["一般宝石", "Normal Gem"], 
["体力之羽", "Health Feather"], 
["肌力之羽", "Muscle Feather"], 
["抵抗之羽", "Resist Feather"], 
["智力之羽", "Genius Feather"], 
["精神之羽", "Clever Feather"], 
["瞬发之羽", "Swift Feather"], 
["美丽之羽", "Pretty Feather"], 
["梦境球", "Dream Ball"], 
["芳香蘑菇", "Balm Mushroom"], 
["巨大金珠", "Big Nugget"], 
["丸子珍珠", "Pearl String"], 
["彗星碎片", "Comet Shard"], 
["招式学习器９３", "TM93"], 
["招式学习器９４", "TM94"], 
["招式学习器９５", "TM95"], 
["弱点保险", "Weakness Policy"], 
["突击背心", "Assault Vest"], 
["妖精石板", "Pixie Plate"], 
["特性胶囊", "Ability Capsule"], 
["光苔", "Luminous Moss"], 
["雪球", "Snowball"], 
["防尘护目镜", "Safety Goggles"], 
["洛玫果", "Roseli Berry"], 
["亚开果", "Kee Berry"], 
["香罗果", "Maranga Berry"], 
["招式学习器９６", "TM96"], 
["招式学习器９７", "TM97"], 
["招式学习器９８", "TM98"], 
["招式学习器９９", "TM99"], 
["密阿雷格雷派饼", "Lumiose Galette"], 
["娑罗沙布蕾", "Shalour Sable"], 
["银色王冠", "Bottle Cap"], 
["金色王冠", "Gold Bottle Cap"], 
["胆怯球", "Adrenaline Orb"], 
["冰之石", "Ice Stone"], 
["究极球", "Beast Ball"], 
["朱红色花蜜", "Red Nectar"], 
["金黄色花蜜", "Yellow Nectar"], 
["桃粉色花蜜", "Pink Nectar"], 
["兰紫色花蜜", "Purple Nectar"], 
["大地膜", "Terrain Extender"], 
["部位护具", "Protective Pads"], 
["电气种子", "Electric Seed"], 
["精神种子", "Psychic Seed"], 
["薄雾种子", "Misty Seed"], 
["青草种子", "Grassy Seed"], 
["腐朽的剑", "Rusted Sword"], 
["腐朽的盾", "Rusted Shield"], 
["草莓糖饰", "Strawberry Sweet"], 
["爱心糖饰", "Love Sweet"], 
["野莓糖饰", "Berry Sweet"], 
["幸运草糖饰", "Clover Sweet"], 
["花朵糖饰", "Flower Sweet"], 
["星星糖饰", "Star Sweet"], 
["蝴蝶结糖饰", "Ribbon Sweet"], 
["甜甜苹果", "Sweet Apple"], 
["酸酸苹果", "Tart Apple"], 
["爽喉喷雾", "Throat Spray"], 
["避难背包", "Eject Pack"], 
["厚底靴", "Heavy-Duty Boots"], 
["打空保险", "Blunder Policy"], 
["客房服务", "Room Service"], 
["万能伞", "Utility Umbrella"], 
["经验糖果ＸＳ", "Exp. Candy XS"], 
["经验糖果Ｓ", "Exp. Candy S"], 
["经验糖果Ｍ", "Exp. Candy M"], 
["经验糖果Ｌ", "Exp. Candy L"], 
["经验糖果ＸＬ", "Exp. Candy XL"], 
["招式学习器００", "TM00"], 
["怕寂寞薄荷", "Lonely Mint"], 
["固执薄荷", "Adamant Mint"], 
["顽皮薄荷", "Naughty Mint"], 
["勇敢薄荷", "Brave Mint"], 
["大胆薄荷", "Bold Mint"], 
["淘气薄荷", "Impish Mint"], 
["乐天薄荷", "Lax Mint"], 
["悠闲薄荷", "Relaxed Mint"], 
["内敛薄荷", "Modest Mint"], 
["慢吞吞薄荷", "Mild Mint"], 
["马虎薄荷", "Rash Mint"], 
["冷静薄荷", "Quiet Mint"], 
["温和薄荷", "Calm Mint"], 
["温顺薄荷", "Gentle Mint"], 
["慎重薄荷", "Careful Mint"], 
["自大薄荷", "Sassy Mint"], 
["胆小薄荷", "Timid Mint"], 
["急躁薄荷", "Hasty Mint"], 
["爽朗薄荷", "Jolly Mint"], 
["天真薄荷", "Naive Mint"], 
["认真薄荷", "Serious Mint"], 
["破裂的茶壶", "Cracked Pot"], 
["缺损的茶壶", "Chipped Pot"], 
["伽勒豆蔻枝", "Galarica Twig"], 
["伽勒豆蔻手环", "Galarica Cuff"], 
["伽勒豆蔻花圈", "Galarica Wreath"], 
["特性膏药", "Ability Patch"], 
["大金刚宝玉", "Adamant Crystal"], 
["大白宝玉", "Lustrous Globe"], 
["大白金宝玉", "Griseous Core"], 
["奇异球", "Strange Ball"], 
["小竹笋", "Tiny Bamboo Shoot"], 
["大竹笋", "Big Bamboo Shoot"], 
["咒术之铠", "Malicious Armor"], 
["一般太晶碎块", "Normal Tera Shard"], 
["火太晶碎块", "Fire Tera Shard"], 
["水太晶碎块", "Water Tera Shard"], 
["电太晶碎块", "Electric Tera Shard"], 
["草太晶碎块", "Grass Tera Shard"], 
["冰太晶碎块", "Ice Tera Shard"], 
["格斗太晶碎块", "Fighting Tera Shard"], 
["毒太晶碎块", "Poison Tera Shard"], 
["地面太晶碎块", "Ground Tera Shard"], 
["飞行太晶碎块", "Flying Tera Shard"], 
["超能力太晶碎块", "Psychic Tera Shard"], 
["虫太晶碎块", "Bug Tera Shard"], 
["岩石太晶碎块", "Rock Tera Shard"], 
["幽灵太晶碎块", "Ghost Tera Shard"], 
["龙太晶碎块", "Dragon Tera Shard"], 
["恶太晶碎块", "Dark Tera Shard"], 
["钢太晶碎块", "Steel Tera Shard"], 
["妖精太晶碎块", "Fairy Tera Shard"], 
["驱劲能量", "Booster Energy"], 
["特性护具", "Ability Shield"], 
["清净坠饰", "Clear Amulet"], 
["模仿香草", "Mirror Herb"], 
["拳击手套", "Punching Glove"], 
["密探斗篷", "Covert Cloak"], 
["机变骰子", "Loaded Dice"], 
["招式学习器１００", "TM100"], 
["招式学习器１０１", "TM101"], 
["招式学习器１０２", "TM102"], 
["招式学习器１０３", "TM103"], 
["招式学习器１０４", "TM104"], 
["招式学习器１０５", "TM105"], 
["招式学习器１０６", "TM106"], 
["招式学习器１０７", "TM107"], 
["招式学习器１０８", "TM108"], 
["招式学习器１０９", "TM109"], 
["招式学习器１１０", "TM110"], 
["招式学习器１１１", "TM111"], 
["招式学习器１１２", "TM112"], 
["招式学习器１１３", "TM113"], 
["招式学习器１１４", "TM114"], 
["招式学习器１１５", "TM115"], 
["招式学习器１１６", "TM116"], 
["招式学习器１１７", "TM117"], 
["招式学习器１１８", "TM118"], 
["招式学习器１１９", "TM119"], 
["招式学习器１２０", "TM120"], 
["招式学习器１２１", "TM121"], 
["招式学习器１２２", "TM122"], 
["招式学习器１２３", "TM123"], 
["招式学习器１２４", "TM124"], 
["招式学习器１２５", "TM125"], 
["招式学习器１２６", "TM126"], 
["招式学习器１２７", "TM127"], 
["招式学习器１２８", "TM128"], 
["招式学习器１２９", "TM129"], 
["招式学习器１３０", "TM130"], 
["招式学习器１３１", "TM131"], 
["招式学习器１３２", "TM132"], 
["招式学习器１３３", "TM133"], 
["招式学习器１３４", "TM134"], 
["招式学习器１３５", "TM135"], 
["招式学习器１３６", "TM136"], 
["招式学习器１３７", "TM137"], 
["招式学习器１３８", "TM138"], 
["招式学习器１３９", "TM139"], 
["招式学习器１４０", "TM140"], 
["招式学习器１４１", "TM141"], 
["招式学习器１４２", "TM142"], 
["招式学习器１４３", "TM143"], 
["招式学习器１４４", "TM144"], 
["招式学习器１４５", "TM145"], 
["招式学习器１４６", "TM146"], 
["招式学习器１４７", "TM147"], 
["招式学习器１４８", "TM148"], 
["招式学习器１４９", "TM149"], 
["招式学习器１５０", "TM150"], 
["招式学习器１５１", "TM151"], 
["招式学习器１５２", "TM152"], 
["招式学习器１５３", "TM153"], 
["招式学习器１５４", "TM154"], 
["招式学习器１５５", "TM155"], 
["招式学习器１５６", "TM156"], 
["招式学习器１５７", "TM157"], 
["招式学习器１５８", "TM158"], 
["招式学习器１５９", "TM159"], 
["招式学习器１６０", "TM160"], 
["招式学习器１６１", "TM161"], 
["招式学习器１６２", "TM162"], 
["招式学习器１６３", "TM163"], 
["招式学习器１６４", "TM164"], 
["招式学习器１６５", "TM165"], 
["招式学习器１６６", "TM166"], 
["招式学习器１６７", "TM167"], 
["招式学习器１６８", "TM168"], 
["招式学习器１６９", "TM169"], 
["招式学习器１７０", "TM170"], 
["招式学习器１７１", "TM171"], 
["招式学习器１７２", "TM172"], 
["招式学习器１７３", "TM173"], 
["招式学习器１７４", "TM174"], 
["招式学习器１７５", "TM175"], 
["招式学习器１７６", "TM176"], 
["招式学习器１７７", "TM177"], 
["招式学习器１７８", "TM178"], 
["招式学习器１７９", "TM179"], 
["招式学习器１８０", "TM180"], 
["招式学习器１８１", "TM181"], 
["招式学习器１８２", "TM182"], 
["招式学习器１８３", "TM183"], 
["招式学习器１８４", "TM184"], 
["招式学习器１８５", "TM185"], 
["招式学习器１８６", "TM186"], 
["招式学习器１８７", "TM187"], 
["招式学习器１８８", "TM188"], 
["招式学习器１８９", "TM189"], 
["招式学习器１９０", "TM190"], 
["招式学习器１９１", "TM191"], 
["招式学习器１９２", "TM192"], 
["招式学习器１９３", "TM193"], 
["招式学习器１９４", "TM194"], 
["招式学习器１９５", "TM195"], 
["招式学习器１９６", "TM196"], 
["招式学习器１９７", "TM197"], 
["招式学习器１９８", "TM198"], 
["招式学习器１９９", "TM199"], 
["招式学习器２００", "TM200"], 
["招式学习器２０１", "TM201"], 
["招式学习器２０２", "TM202"], 
["招式学习器２０３", "TM203"], 
["招式学习器２０４", "TM204"], 
["招式学习器２０５", "TM205"], 
["招式学习器２０６", "TM206"], 
["招式学习器２０７", "TM207"], 
["招式学习器２０８", "TM208"], 
["招式学习器２０９", "TM209"], 
["招式学习器２１０", "TM210"], 
["招式学习器２１１", "TM211"], 
["招式学习器２１２", "TM212"], 
["招式学习器２１３", "TM213"], 
["招式学习器２１４", "TM214"], 
["招式学习器２１５", "TM215"], 
["招式学习器２１６", "TM216"], 
["招式学习器２１７", "TM217"], 
["招式学习器２１８", "TM218"], 
["招式学习器２１９", "TM219"], 
["招式学习器２２０", "TM220"], 
["招式学习器２２１", "TM221"], 
["招式学习器２２２", "TM222"], 
["招式学习器２２３", "TM223"], 
["招式学习器２２４", "TM224"], 
["招式学习器２２５", "TM225"], 
["招式学习器２２６", "TM226"], 
["招式学习器２２７", "TM227"], 
["招式学习器２２８", "TM228"], 
["招式学习器２２９", "TM229"], 
["庆祝之铠", "Auspicious Armor"], 
["头领凭证", "Leader’s Crest"], 
["妖精之羽", "Fairy Feather"], 
["蜜汁苹果", "Syrupy Apple"], 
["凡作茶碗", "Unremarkable Teacup"], 
["杰作茶碗", "Masterpiece Teacup"], 
["础石面具", "Cornerstone Mask"], 
["水井面具", "Wellspring Mask"], 
["火灶面具", "Hearthflame Mask"], 
["体力粘糕", "Health Mochi"], 
["肌力粘糕", "Muscle Mochi"], 
["抵抗粘糕", "Resist Mochi"], 
["智力粘糕", "Genius Mochi"], 
["精神粘糕", "Clever Mochi"], 
["瞬发粘糕", "Swift Mochi"], 
["净空粘糕", "Fresh-Start Mochi"], 
["复合金属", "Metal Alloy"], 
["星晶太晶碎块", "Stellar Tera Shard"]];